# @format
branches:
  only:
    - master

os: linux
dist: focal
language: generic
services:
  - docker
 
jobs:
  include:
    - stage: Building and running the container
      script:
        - docker build -t vcity:morpho .
        - docker run --rm --detach -t vcity:morpho
        - travis_wait 2
        - docker stop $(docker ps -a -q --filter ancestor=vcity:morpho --format="{{.ID}}")

